-- liquibase formatted sql
--changeset amritkthapa:1

--preconditions onFail:CONTINUE onError:HALT

INSERT INTO `email_template` (name, template, created_date, version)
VALUES
    ( 'User Verification', '<!DOCTYPE html>\n<html lang="en">\n<head>\n    <meta charset="UTF-8">\n    <title>Account Verification</title>\n    <style>\n        body {\n            font-family: Arial, sans-serif;\n            background-color: #f4f4f4;\n            margin: 0;\n            padding: 0;\n        }\n        .container {\n            width: 100%;\n            max-width: 600px;\n            margin: 0 auto;\n            background-color: #ffffff;\n            padding: 20px;\n            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\n        }\n        .header {\n            text-align: center;\n            padding: 10px 0;\n            background-color: #007bff;\n            color: #ffffff;\n        }\n        .content {\n            padding: 20px;\n            line-height: 1.6;\n            text-align: justify;\n        }\n        .btn {\n            display: inline-block;\n            background-color: #007bff;\n            color: #ffffff;\n            padding: 10px 20px;\n            text-decoration: none;\n            border-radius: 5px;\n        }\n        .footer {\n            text-align: center;\n            padding: 10px 0;\n            color: #888888;\n            font-size: 12px;\n        }\n    </style>\n</head>\n<body>\n<div class="container">\n    <div class="header">\n        <h1>Account Verification</h1>\n    </div>\n    <div class="content">\n        <p>Dear ${customerUserName},</p>\n        <p>Your account has been created. To verify your email address, please use the following One Time Password (OTP):</p>\n        <p style="text-align: center;">\n             <h1>${OTP},</h2>\n        </p>
       <p>Do not share this OTP with anyone. CosmoTech takes your account security very seriously. CosmoTech Customer Service will never ask you to disclose or verify your Account''s password, OTP. If you receive a suspicious email with a link to update your account information, do not click on the link—instead, report the email to CosmoTech for investigation.</p>\n <p>This OTP will expire in 2 minutes.</p>\n        <p>Best regards,<br/>Cosmotech International Pvt. Ltd.</p>\n    </div>\n    <div class="footer">\n        <p>&copy; ${currentYear} Cosmotech International Pvt. Ltd. All rights reserved.</p>\n    </div>\n</div>\n</body>\n</html>', NOW(), 0);
